[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
ledger_verify_sig = "7AcjcnULkoipLpqzZGkCmTqM4YTNCKeLSPx6vjXBhBRK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

